services:
  app:
    build:
      context: ./docker/php-fpm
    container_name: blog-app
    volumes:
      - ./src:/var/www/html
      - ./.env:/var/www/html/.env:ro
      - ./docker/php-fpm/99-custom.ini:/usr/local/etc/php/conf.d/99-custom.ini:ro
      - ./docker/php-fpm/zz-dynamic.conf:/usr/local/etc/php-fpm.d/zz-dynamic.conf:ro
    working_dir: /var/www/html
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - blog-network
    restart: unless-stopped

  web:
    image: nginx:stable-alpine
    container_name: blog-web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - blog-network
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: blog-db
    # env_file:
    #   - .env
    environment:
      - POSTGRES_DB=blog_cms
      - POSTGRES_USER=laraveluser
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - blog-network
    restart: unless-stopped

  # nphung/pgadmin
  pgadmin:
    # image: nphung/pgadmin
    image: dpage/pgadmin4:9.4.0
    container_name: blog-pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: secret
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - blog-network
    restart: unless-stopped


  redis:
    image: redis:7-alpine
    container_name: blog-redis
    environment:
      - REDIS_PASSWORD=null
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - blog-network
    restart: unless-stopped

networks:
  blog-network:

volumes:
  pgdata:
  pgadmin_data:
