version: '3.8'

services:
  app:
    image: yourdockerhubusername/lara-app:latest
    env_file:
      - .env.production
    restart: always
    networks:
      - blog-network

  web:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - blog-network

  db:
    image: postgres:16-alpine
    # env_file:
    #   - .env.production
    environment:
      - POSTGRES_DB=blog_cms
      - POSTGRES_USER=laraveluser
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    networks:
      - blog-network
  
  redis:
    image: redis:7-alpine
    container_name: blog-redis
    environment:
      - REDIS_PASSWORD=null
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - blog-network
    restart: unless-stopped

networks:
  blog-network:
    driver: bridge

volumes:
  db_data:
